### ISSUE TITLE
Account details not saved

### ISSUE THREAD

**Issue by saundlj** [saundlj/AgileWebProj#23]
If i change the account details and then refresh the page, it doesn't update to the changes... 
I think it should be a simple change in the routes.py.
@tomve1tch can you take a look at this?

**Comment by tomve1tch** [comment]
Hi @saundlj, it should be working. Right now the values stored by the form are not being displayed on the account page as someone deleted the code I wrote for that :( 
Will try add it back in to display the account information. From a back-end perspective it should be working though.

**Comment by saundlj** [comment]
I tried again and its still not working. The changes save on the page after I update my bio, but as soon as i move to another url or logout the changes are not visable and go back to default.
